version: "3.3"

services:
  ms_auth:
    build:
      dockerfile: Dockerfile
      context: .

    depends_on:
      - my_sql
    networks:
      - api-networks
    ports:
      - "9090:9090"
  my_sql:
    image: mysql
    container_name: authen_db
    environment:
      - MYSQL_ROOT_PASSWORD=147563
      - MYSQL_DATABASE=app_auth
      - MYSQL_USER=users
      - MYSQL_PASSWORD=147563
    # ports:
    #   - "3306:3306"
    networks:
      - api-networks

networks:
  api-networks:
    driver: bridge
# docker run --name my_sql -e MYSQL_ROOT_PASSWORD=147563 -e MYSQL_PASSWORD=147563 -e MYSQL_USER=users -e MYSQL_DATABASE=app_auth -p 3306:3306  -d mysql:latest
