version: "3.3"

services:
  ms_gmail:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: ms_gmail
    restart: always
    ports:
      - "8080:8080"
    networks:
      - api-networks
networks:
  api-networks:
